Piece.create(title: "The Starry Night" , artist: "Vincent van Gogh" , desc: " \"This morning I saw the country from my window a long time before sunrise, with nothing but the morning star, which looked very big,\" van Gogh wrote to his brother Theo, from France. Rooted in imagination and memory, The Starry Night embodies an inner, subjective expression of van Gogh's response to nature. In thick, sweeping brushstrokes, a flamelike cypress unites the churning sky and the quiet village below. The village was partly invented, and the church spire evokes van Gogh's native land, the Netherlands.", date: "June 1889")

Piece.create(title: "The Persistence of Memory
",artist: "Salvador Dalí",desc:"Dalí rendered his fantastic visions with meticulous verisimilitude, giving the representations of dreams a tangible and credible appearance. In what he called \"hand painted dream photographs,\" hard objects become inexplicably limp, time bends, and metal attracts ants like rotting flesh. The monstrous creature draped across the painting's center resembles the artist's own face in profile; its long eyelashes seem insectlike or even sexual, as does what may or may not be a tongue oozing from its nose like a fat snail.",date:"1931")

Piece.create(title: "Christina\'s World",artist: "Andrew Wyeth",desc: "The woman crawling through the tawny grass was the artist's neighbor in Maine, who, crippled by polio, \"was limited physically but by no means spiritually.\" Wyeth further explained, \"The challenge to me was to do justice to her extraordinary conquest of a life which most people would consider hopeless.\" He recorded the arid landscape, rural house, and shacks with great detail, painting minute blades of grass, individual strands of hair, and nuances of light and shadow. In this style of painting, known as magic realism, everyday scenes are imbued with poetic mystery.",date: "1948")

Piece.create(title:"Les Demoiselles d'Avignon",artist:"Pablo Picasso",desc: "Les Demoiselles d’Avignon marks a radical break from traditional composition and perspective in painting. It depicts five naked women with figures composed of flat, splintered planes and faces inspired by Iberian sculpture and African masks. The compressed space the figures inhabit appears to project forward in jagged shards; a fiercely pointed slice of melon in the still life of fruit at the bottom of the composition teeters on an impossibly upturned tabletop. Picasso unveiled the monumental painting in his Paris studio after months of revision. The Avignon of the work’s title is a reference to a street in Barcelona famed for its brothel. In Picasso’s preparatory studies for the work, the figure at the left was a man, but the artist eliminated this anecdotal detail in the final painting.",date:"June-July 1907")

Piece.create(title: "Drowning Girl",artist: "Roy Lichtenstein",desc: "Lichtenstein based many of his early paintings on imagery he found in comic books. The source for this work is Run for Love! published by DC Comics in 1962, the cover of which the artist significantly altered to arrive at the finished composition. In the original illustration, the drowning girl’s boyfriend appears in the background, clinging to a capsized boat. Lichtenstein cropped the image dramatically, showing the girl alone and encircled by a threatening wave. He changed the caption from \“I don’t care if I have a cramp!\” to \“I don’t care!\” and the boyfriend’s name from Mal to Brad. In addition to appropriating comic books’ melodramatic content, Lichtenstein manually simulated the Benday dots used in the mechanical reproduction of images.",date: "1963")

Piece.create(artist: "The Lovers",title: "Ren\é Magritte",date: "1928",desc: "In this unsettling image—the first in a series of four variations of Les Amants that Magritte painted in 1928—the artist invokes the cinematic cliché of a close–up kiss but subverts our voyeuristic pleasure by shrouding the faces in cloth. The device of a draped cloth or veil to conceal a figure’s identity corresponds to a larger Surrealist interest in masks, disguises, and what lies beyond or beneath visible surfaces. The melodramatic scene may also relate to the graphic illustrations that accompanied pulp fiction and thriller stories, which Magritte's friend Paul Nougé, in a letter from 1927, encouraged the artist to emulate.")

Piece.create(title: "The Sleeping Gypsy
",artist: "Henri Rousseau",desc: "Rousseau, a toll collector for the city of Paris, was largely a self-taught painter, although he had ambitions of entering the Academy. This was never realized, but the sharp colors, fantastic imagery, and precise outlines in his work—derived from the style and subject matter of popular print culture—struck a chord with a younger generation of avant-garde painters. Rousseau described the subject of The Sleeping Gypsy thus: \"A mandolin player, lies with her jar beside her (a vase with drinking water), overcome by fatigue in a deep sleep. A lion chances to pass by, picks up her scent yet does not devour her. There is a moonlight effect, very poetic.\"",date: "1897")

Piece.create(title: "I and the Village",artist: "Marc Chagall",date: "1911")

Piece.create(title: "Campbell's Soup Cans",artist: "Andy Warhol",desc: "When Warhol first exhibited these thirty-two canvases in 1962, each one simultaneously hung from the wall like a painting and rested on a shelf like groceries in a store. The number of canvases corresponds to the varieties of soup then sold by the Campbell Soup Company. Warhol assigned a different flavor to each painting, referring to a product list supplied by Campbell's. There is no evidence that Warhol envisioned the canvases in a particular sequence.",date: "1962")

Piece.create(title: "Seated Woman",artist: "Pablo Picasso",date: "1927")
Piece.create(title: "Girl before a Mirror" ,artist: "Pablo Picasso",date: "March 14, 1932")
Piece.create(title: "The City Rises",artist: "Umberto Boccioni",date: "1910")







Piece.create(title: "One: Number 31, 1950",artist: "Jackson Pollock",desc: "This is one of three wall-size paintings that Pollock realized in swift succession in the summer and autumn of 1950. In 1947, Pollock began laying canvas on the floor and pouring, dribbling, and flicking enamel paint onto the surface, sometimes straight from the can, or with sticks and stiffened brushes. The density of interlacing liquid threads of paint is balanced and offset by puddles of muted colors and by allover spattering. The pictorial result of this tension is a landmark in the history of Abstract Expressionism.",date: "1950")

Piece.create(title: "Broadway Boogie Woogie",artist: "Piet Mondrian",desc: "Mondrian, who had escaped to New York from Europe after the outbreak of World War II, delighted in the city's architecture. He was also fascinated by American jazz, particularly boogie-woogie, finding its syncopated beat, irreverent approach to melody, and improvisational aesthetic akin to what he called, in his own work, the \"destruction of natural appearance; and construction through continuous opposition of pure means—dynamic rhythm.\" In this painting, his penultimate, Mondrian replaced the black grid that had long governed his canvases with predominantly yellow lines that intersect at points marked by squares of blue and red. These atomized bands of stuttering chromatic pulses, interrupted by light gray, create paths across the canvas suggesting the city's grid, the movement of traffic, and blinking electric lights, as well as the rhythms of jazz.",date: "1942-43")

Piece.create(title: "Bicycle Wheel
",artist: "Marcel Duchamp",desc: "Bicycle Wheel is Duchamp’s first readymade, a class of objects he invented to challenge assumptions about what constitutes a work of art. Duchamp combined two mass-produced parts—a bicycle wheel and fork and a kitchen stool—to create a type of nonfunctional machine. By simply selecting prefabricated items and calling them art, he subverted established notions of the artist’s craft and the viewer’s aesthetic experience. The 1913 Bicycle Wheel was lost, but nearly four decades later Duchamp assembled a replacement from newly found prefabricated parts and affirmed that the later version is as valid as the original.",date: "New York, 1951 (third version, after lost original of 1913)")

Piece.create(title: "Suprematist Composition: White on White",artist: "Kazimir Malevich",desc: "Malevich described his aesthetic theory, known as Suprematism, as \"the supremacy of pure feeling or perception in the pictorial arts.\" He viewed the Russian Revolution as having paved the way for a new society in which materialism would eventually lead to spiritual freedom. This austere painting counts among the most radical paintings of its day, yet it is not impersonal; the trace of the artist's hand is visible in the texture of the paint and the subtle variations of white. The imprecise outlines of the asymmetrical square generate a feeling of infinite space rather than definite borders.",date: "1918")

Piece.create(title: "Woman I",artist: "Willem de Kooning",desc: "De Kooning famously said, \"Flesh is the reason oil paint was invented.\" Woman I was one of a series of six paintings centered upon a female figure that de Kooning worked on from 1950 to 1953. Here, he took the opportunity to further experiment with the wide-ranging methods of applying paint to canvas, exploring the physical possibilities of the medium. Although it may appear rapidly and intuitively executed, De Kooning made numerous preliminary studies then repainted the canvas repeatedly—scraping away and re-working the image, over nearly two years",date: "1950–52")

Piece.create(title: "The False Mirror",artist: "René Magritte",desc: "Le Faux Miroir presents an enormous lashless eye with a luminous cloud-swept blue sky filling the iris and an opaque, dead-black disc for a pupil. The allusive title, provided by the Belgian Surrealist writer Paul Nougé, seems to insinuate limits to the authority of optical vision: a mirror provides a mechanical reflection, but the eye is selective and subjective. Magritte’s single eye functions on multiple enigmatic levels: the viewer both looks through it, as through a window, and is looked at by it, thus seeing and being seen simultaneously. The Surrealist photographer Man Ray, who owned the work from 1933 to 1936, recognized this compelling duality when he memorably described Le Faux Miroir as a painting that \“sees as much as it itself is seen.\” ",date: "1929")

Piece.create(title: "The Bather",artist: "Paul Cezanne",date: "c. 1885")

Piece.create(title: "Girl with a Mandolin (Fanny Tellier)",artist: "Pablo Picasso" ,date: "late spring 1910")

Piece.create(title: "The Reservoir, Horta de Ebro",artist: "Pablo Picasso",desc:"The landscapes Picasso produced in Spain in 1909 were critical to the development of the early Cubist style, in which subjects are rendered from multiple perspectives using faceted forms and simplified geometric shapes. In The Reservoir, Horta de Ebro (titled using the artist's name for the town of Horta de San Joan), Picasso used interlocking planes to fuse the land's rugged topography with the terracotta and stucco architecture of the village. The spatial ambiguity characteristic of Cubism is evident: the steep hillside suggests an upward gaze while the curved shape at the bottom—a cistern—reveals a downward view into a reflection on water.",date: "summer 1909")

Piece.create(title: "Two Nudes",artist: "Pablo Picasso",date: "late 1906")
Piece.create(title: "Object",artist: "Meret Oppenheim",desc: "This Surrealist object was inspired by a conversation between Oppenheim and artists Pablo Picasso and Dora Maar at a Paris cafe. Admiring Oppenheim's fur-covered bracelet, Picasso remarked that one could cover anything with fur, to which she replied, \"Even this cup and saucer.\" Soon after, when asked by André Breton, Surrealism's leader, to participate in the first Surrealist exhibition dedicated to objects, Oppenheim bought a teacup, saucer, and spoon at a department store and covered them with the fur of a Chinese gazelle. In so doing, she transformed genteel items traditionally associated with feminine decorum into sensuous, sexually punning tableware.",date: "1936")

Piece.create(title: "House by the Railroad",artist: "Edward Hopper",desc: "Edward Hopper produced closely observed urban views, landscapes (largely of New England), and interior scenes—all either devoid of or sparsely populated by people. Though he insisted that his paintings were straightforward representations of the real world, their overall sparseness imbues them with a sense of loneliness, estrangement, and stillness. Light, whether from electric bulbs or the sun, defines the places he depicts and shapes the mood of his works. A late afternoon glow pervades House by the Railroad, which features a grand Victorian home fronted by the tracks of a railroad. The tracks create a visual barrier that seems to block access to house, which appears moored and isolated in the surrounding empty landscape. Its old-fashioned architecture and lack of any sense of occupancy imply that the house may be a relic of tradition, lonely and forgotten in the push towards urbanization and progress, as suggested by the railroad tracks.",date:"1925")

Piece.create(title: "Hope, II",artist: "Gustav Klimt",desc: "Although images of women and children are frequent in the history of art, depictions of pregnancy are rare. In Hope, II a woman with a skull nestled into her gown lowers her head toward her swelling belly. Below, three women also bow their heads—in prayer or possibly mourning. The ornate decoration in Hope, II nearly overwhelms its surface. Klimt was committed to craft work, and was among the many artists of his time who combined archaic traditions—here Byzantine gold leaf painting—with a modern psychological subject. Klimt lived and worked in turn-of-the-century Vienna, home to Sigmund Freud, the father of psychoanalysis; Klimt's exploration of formative drives like sex and death parallel Freud's explorations of the psyche.",date: "1907-08")

Piece.create(title: "Self-Portrait with Cropped Hair",artist: "Frida Kahlo",desc: "Though the Surrealists adopted Frida Kahlo as one of their own, the painter maintained that she did “not know if my paintings are Surrealist or not, but I do know that they are the most frank expression of myself.” She produced numerous self-portraits, each one an articulation of different facets of herself and her eventful life. Kahlo painted Self-Portrait with Cropped Hair in the wake of a particularly tumultuous time, just months after she divorced her famous husband, Mexican Muralist painter Diego Rivera. He had always admired her long, dark hair, which, as she indicates in the tresses littering the painting, she had cut off after their split. She also shows herself in an oversized suit resembling the ones that Rivera wore. Through such emotionally and symbolically charged details, Kahlo expresses her feelings about her relationship with Rivera while also asserting her sense of self as an independent artist.",date: "1940")

Piece.create(title: "Fulang-Chang and I",artist: "Frida Kahlo",desc: "Fulang-Chang and I depicts Kahlo with one of her pet monkeys, interpreted by many as surrogates for the children she and Diego Rivera were unable to conceive. The painting was included in the first major exhibition of her work, held at Julien Levy Gallery in New York in 1938. In the essay that accompanied the show, the Surrealist leader André Breton described Kahlo's work as \"a ribbon around a bomb\" and hailed her as a self-created Surrealist painter. Although she appreciated his enthusiasm for her work, Kahlo did not agree with his assessment: \"They thought I was a Surrealist but I wasn’t. I never painted dreams. I painted my own reality.\" Kahlo later gave this painting to her close friend Mary Sklar, attaching a mirror to it so that, if Sklar chose, the two friends could be together.",date: "1937 (assembled after 1939)")

Piece.create(title: "The Blue Window",artist: "Henri Matisse",desc: "When this painting was first reproduced, in the May 1914 edition of the journal Les Soirées de Paris, it was titled La Glace sans tain, or \"the mirror without silvering,\" referring to a device known as a Claude mirror: the dark, red-framed square in the picture. Many artists used one of these slightly convex, dark-tinted mirrors to clarify their compositions; a scene reflected in it is less colorful than life, its compositional elements accentuated. Something close to that effect is visible here in the structured vertical and horizontal bands and the cool blue palette that Matisse painted over other layers of color, some of which are still visible. As he simplified forms he reinforced them with incising and scraping, in, for example, the cloud at top left.",date: "summer 1913")

Piece.create(title: "Gold Marilyn Monroe",artist: "Andy Warhol",desc: "Warhol made this painting the year screen legend Marilyn Monroe committed suicide. He painted the canvas an iridescent gold and silkscreened the star’s face in the center of the composition. Like other paintings by Warhol that feature Monroe’s likeness, this work is based on a 1953 publicity still for the movie Niagara. By duplicating a photograph known to millions, Warhol undermined the uniqueness and authenticity characteristic of traditional portraiture. Instead he presented Monroe as an infinitely reproducible image.",date: "1962")

Piece.create(title: "Mlle Pogany",artist: "Constantin Brancusi",desc: "This sculpture is a portrait of Margit Pogany, a Hungarian artist who sat for Brancusi several times in 1910 and 1911 while she was in Paris studying painting. Shortly after her return to Hungary, Brancusi carved a marble Mlle Pogany from memory, then made a plaster mold of the work, from which he cast four additional versions, including this one, in bronze. In representing its subject through highly stylized and simplified forms, the work was a significant departure from conventional portraiture. Large almond-shaped eyes overwhelm the oval face, and a black patina represents the hair that covers the top of the head and extends over the elaborate chignon at the nape of the neck. As with other motifs, this was a subject Brancusi would return to and rework in the years to come.",date: "1913 (after a marble of 1912)")




####
Piece.create(title: "Ma Jolie",artist: "Pablo Picasso",desc: "Ma jolie (My pretty girl) was the refrain of a popular song performed at a Parisian music hall Picasso frequented. The artist suggests this musical association by situating a treble clef and music staff near the bold, stenciled letters. Ma jolie was also Picasso's nickname for his lover Marcelle Humbert, whose figure he loosely built using the signature shifting planes of Analytic Cubism. This is far from a traditional portrait, but there are clues to its representational content. The central triangular mass subtly indicates the shape of a woman's head and torso, and a group of six vertical lines at the painting's lower center represent the strings of a guitar, which the woman strums. In Cubist works of this period, Picasso and Georges Braque employed multiple modes of representation simultaneously: here, Picasso combined language (in the black lettering), symbolic meaning (in the treble clef), and near abstraction (in the depiction of his subject).",date: "1911-12")

Piece.create(title: "The Menaced Assassin",artist: "René Magritte",desc: "The Menaced Assassin is one of Magritte's largest and most theatrical compositions. Magritte was an avid fan of the pre-World War I popular crime fiction series Fantômas; he borrowed the placement of the two detectives' figures flanking the door frame from the Le Mort Qui Tue (The Murderous Corpse), a film from the series first released in 1913. It was Magritte's ambition to create a similarly immersive and fantastical world on the canvas, here made manifest in the unsolvable narrative of this enduringly mysterious painting.",date: "1927")

Piece.create(title: "Vir Heroicus Sublimis",artist: "Barnett Newman",desc: "The Latin title of this painting can be translated as \"Man, heroic and sublime.\" It refers to Newman’s essay \"The Sublime is Now,\" in which he asks, \"If we are living in a time without a legend that can be called sublime, how can we be creating sublime art?\" His response is embodied in part by this painting—his largest ever at that time. Newman hoped that the viewer would stand close to this expansive work, and he likened the experience to a human encounter: \"It's no different, really, from meeting another person. One has a reaction to the person physically. Also, there’s a metaphysical thing, and if a meeting of people is meaningful, it affects both their lives\"",date: "1950-51")

Piece.create(title: "Still Life with Fruit Dish",artist: "Paul Cezanne",desc: "Still life was an important genre to Cézanne, who made approximately two hundred such paintings over the course of four decades. In Still Life with Fruit Dish he created a shallow, compressed space that flattens the sculptural volumes of dish, glass, and fruit. This painting was a prized possession of the artist Paul Gauguin, who described the picture as \"an exceptional pearl, the apple of my eye.\" It was only when he needed money for medical care that Gauguin unhappily parted with it.",date: "1879-80")

Piece.create(title:"Still Life with Apples",artist: "Paul Cezanne",desc: "
Still Life with Apples demonstrates that the genre of still life can be a vehicle for faithfully representing not only objects but also the appearance of light and space. Painting from nature is not copying the object, Cézanne wrote, it is realizing ones sensations. He consistently drew attention to the quality of the paint and canvasnever aiming for illusion. For example, the edges of the fruit in the bowl are undefined and appear to shift. Rules of perspective, too, are broken; the right corner of the table tilts forward and is not aligned with the left side. Some areas of canvas are left bare, and others, like the drape of the tablecloth, appear unfinished. Still Life with Apples is more than an imitation of lifeit is an exploration of seeing and the very nature of painting.",date:"1895-98")

Piece.create(title: "One and Three Chairs",artist: "Joseph Kosuth",desc: "A chair sits alongside a photograph of a chair and a dictionary definition of the word chair. Perhaps all three are chairs, or codes for one: a visual code, a verbal code, and a code in the language of objects, that is, a chair of wood. But isn't this last chair simply . . . a chair? Or, as Marcel Duchamp asked in his Bicycle Wheel of 1913, does the inclusion of an object in an artwork somehow change it? If both photograph and words describe a chair, how is their functioning different from that of the real chair, and what is Kosuth's artwork doing by adding these functions together? Prodded to ask such questions, the viewer embarks on the basic processes demanded by Conceptual art.",date: "1965")

Piece.create(title: "The Song of Love",artist: "Giorgio de Chirico",desc: " \"M. Giorgio de Chirico has just bought a red rubber glove\"—so wrote the French poet Guillaume Apollinaire in July of 1914, noting the purchase because, he went on to say, he knew the glove's appearance in de Chirico's paintings would add to their uncanny power. Implying human presence, as a mold of the hand, yet also inhuman, a clammily limp fragment distinctly unfleshlike in color, the glove in The Song of Love has an unsettling authority. Why, too, is this surgical garment pinned to a board or canvas, alongside a plaster head copied from a classical statue, relic of a noble vanished age? What is the meaning of the green ball? And what is the whole ensemble doing in the outdoor setting insinuated by the building and the passing train?",date: " June-July 1914")

Piece.create(title: "Endless Column",artist: "Constantin Brancusi",desc: "This sculpture is the earliest extant Endless Column. In preceding years Brancusi had used a single or double pyramid as a base for his sculpture, but he eventually came to see this abstract construction as a fully realized work in its own right. Carved from oak, this succession of pyramids forms a rhythmic and undulating geometry that suggests the possibility of infinite expansion. Like other favorite motifs, this was one that Brancusi would return to over the course of his career. In the mid-1920s, he carved an Endless Column for his friend the photographer Edward Steichen that rose more than twenty-three feet. And in 1937 Brancusi erected a steel Endless Column in Tîrgu-Jiu, Romania, that soared more than ninety-eight feet into the air. That Endless Column, his last, was part of a larger sculptural ensemble that included The Gate of the Kiss and Table of Silence, which formed the artist’s only foray into public sculpture.
",date: "1918")
Piece.create(title: "Woman with a Mandolin",artist: "Georges Braque",date: "1937")


Piece.create(title: "Bauhaus Stairway",artist: "Oskar Schlemmer",desc: "Bauhaus Stairway depicts the Bauhaus, a school founded in 1919 by architect Walter Gropius, famous for its visionary integration of technology, art, and design. Although Schlemmer made this painting three years after he left his teaching position at the Bauhaus, the works gridded structure, streamlined modular bodies and predominant palette of primary colors capture the schools vibrant design spirit. The carefully choreographed arrangement of the figures and the man en pointe at the top of the stairs reflects Schlemmers role as the creator of many important dance and theatrical productions at the Bauhaus. Schlemmer painted this work as Hitler assumed power, shortly before the Nazis closed the Bauhaus for good. He was among many artists persecuted by the Nazis, whose work they deemed \"degenerate\" and often destroyed.",date: "1932")

Piece.create(title: "The She-Wolf",artist: "Jackson Pollock",desc: "In the early 1940s Pollock, like many of his peers, explored primeval or mythological themes in his work. The wolf in this painting may allude to the animal that suckled the twin founders of Rome, Romulus and Remus, in the myth of the city’s birth. But \“She-Wolf came into existence because I had to paint it,\” Pollock said in 1944. In an attitude typical of his generation, he added, \“Any attempt on my part to say something about it, to attempt explanation of the inexplicable, could only destroy it.\” The She-Wolf was featured in Pollock’s first solo exhibition, at Art of This Century gallery in New York in 1943. MoMA acquired the painting the following year, making it the first work by Pollock to enter a museum collection.",date: "1943")

Piece.create(title: "The Japanese Footbridge",artist: "Claude Monet",desc: "The Japanese Footbridge is among Monet's last paintings of this subject, made between 1920 and 1922. Twenty-five years earlier, in the late 1890s, the footbridge provided the subject of Monet's first series of paintings of his pond at Giverny. While the paintings in the earlier series are more naturalistic in style, the later works feature dense swirls and loose strokes of color that almost obscure the form of the bridge. These later paintings also feature a fiery palette of maroons, rusts, and oranges unique within Monet's body of work.",date: "c. 1920-22")

Piece.create(title: "Girl with Ball",artist: "Roy Lichtenstein",desc: "Lichtenstein took the image for Girl with Ball straight from an advertisement for a hotel in Pennsylvania's Pocono Mountains. In pirating it, however, he transformed the photographic image, using a painter's version of the techniques of the comic-strip artist. The resulting simplifications intensify the artifice of the picture, concentrating its careful evocation of fun in the sun. The girl’s round mouth is more doll-like than female; any sex appeal she had has become as plastic as her beach ball.",date: "1961")
Piece.create(title: "Man with a Guitar",artist: "Georges Braque",desc: "Braque painted Man with a Guitar in a mode that came to be called Analytic Cubism. In works created in this style, he and Pablo Picasso experimented with different types of representation to challenge the orthodoxy of illusionistic space in painting. Here Braque paired an accessible, lifelike rendering of a nail and rope, at left, with a nearly indecipherable rendering of a human figure playing a guitar. Braque and Picasso's collaboration was so close when they developed Analytic Cubism that Braque later compared them to two mountaineers, bound together. In order to remove the mystique of the maker from their paintings, they both habitually signed the back of their works instead of the front.",date: "summer 1911-early 1912")
